apiVersion: promotions.gitopsprom.io/v1alpha1
kind: Promotion
metadata:
  name: from-dev-to-prod
spec:
  sourceEnvironmentRef:
    name: dev
  targetEnvironmentRef:
    name: prod
  copy:
  - name: "Application Version"
    source: app-version
    target: ./
  - name: "Kustomization File"
    source: ./app-version/kustomization.yaml
    target: ./app-version/
  strategy: pull-request
