apiVersion: promotions.gitopsprom.io/v1alpha1
kind: Environment
metadata:
  name: dev
spec:
  path: ./envs/dev
  source:
    url: https://github.com/thomasstxyz/example-kustomize-overlay-dev
    ref:
      branch: main
---
apiVersion: promotions.gitopsprom.io/v1alpha1
kind: Environment
metadata:
  name: prod
spec:
  path: ./envs/prod
  source:
    url: https://github.com/thomasstxyz/example-kustomize-overlay-prod
    ref:
      branch: main
    secretRef:
      name: prod-ssh
  apiTokenSecretRef:
    name: github-api-token
  gitProvider: github
---
apiVersion: promotions.gitopsprom.io/v1alpha1
kind: Environment
metadata:
  name: privaterepo
spec:
  source:
    url: https://github.com/thomasstxyz/privaterepo
    ref:
      branch: main
    secretRef:
      name: privaterepo-ssh
